### ISSUE TITLE
Invalid Submodules

### ISSUE THREAD

**Issue by charlesneimog** [Ircam-Partiels/Partiels#1]
Hi,

Thanks to opensource of Partiels, just to point that the git submodules are invalid.

**Comment by pierreguillot** [comment]
Hi,

Thanks for this first contribution to the repository 😃! I've just imported the repository on GitHub but haven't had a chance to adapt it properly. Nevertheless, you can check the dev/gh which allows to get rid of the dependency. I'll update the branch soon to add GitHub actions, releases, and so on.

**Comment by pierreguillot** [comment]
You should be able to use the main branch now 😉
